Model Building - Random Forest regression

In [40]:
# Creating model object
model_rf = RandomForestClassifier(n_estimators=300,min_samples_leaf=0.16, random_state=42)

In [41]:
x_train

array([[-0.14484136, -0.00473199],
       [-1.01388955,  0.04822804],
       [-1.30357228, -2.52803761],
       [ 1.59325501,  0.89032267],
       [-0.43452409,  0.14537196],
       [ 0.43452409,  0.39773522],
       [-0.72420682, -0.12795607],
       [ 0.14484136,  0.19157468]])

In [42]:
y_train

array([[2008.        ,   73.50628931],
       [2005.        ,   73.76268908],
       [2004.        ,   61.29      ],
       [2014.        ,   77.83959184],
       [2007.        ,   74.233     ],
       [2010.        ,   75.45478723],
       [2006.        ,   72.90971429],
       [2009.        ,   74.45668508]])

In [43]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=44) 



In [44]:
from sklearn.ensemble import RandomForestRegressor


In [45]:

model_rf = RandomForestRegressor (n_estimators=50, max_features="auto", random_state=44) 
model_rf

RandomForestRegressor(n_estimators=50, random_state=44)

In [46]:

model_rf.fit(x_train, y_train)

RandomForestRegressor(n_estimators=50, random_state=44)

In [47]:

pred_rf = model_rf.predict(x_test)
pred_rf

array([[2006.54      ,   73.96217529],
       [2012.16      ,   76.9136783 ],
       [2007.2       ,   74.30292638],
       [2010.48      ,   76.01904282]])

In [48]:
from sklearn.metrics import accuracy_score

In [49]:
# Calculating Accuracy Score
model_rf.score(x_test, y_test)

0.5050696050469521

In [50]:
from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, pred_rf))
print('MSE:', metrics.mean_squared_error(y_test, pred_rf))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test,pred_rf)))

MAE: 0.9571167875216364
MSE: 1.6061903678281326
RMSE: 1.2673556595636968


In [51]:
metrics.r2_score (y_test, pred_rf)

0.5050696050469521

In [52]:
import pickle 
pickle.dump(pred_rf, open('wqi.pkl', 'wb')) 
model = pickle.load(open('wqi.pkl','rb'))